management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: optional:configserver:http://192.168.1.106:10001/all-configs
  application:
    name: mail-processor
  profiles:
    active: prod